[tool.poetry]
name = "zctc"
version = "0.1.0"
description = "CLI tool to build, parse or generate new fst files from the tokenized vocab"
authors = ["durgaivelselvan.mn <durgaivelselvan.mn@zohocorp.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
torch = ">=2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
